#!/usr/bin/env php
<?php
require __DIR__ . '/../../autoload.php';

use BrainMaestro\GitHooks\Hook;
use BrainMaestro\GitHooks\Commands\AddCommand;
use BrainMaestro\GitHooks\Commands\RemoveCommand;
use BrainMaestro\GitHooks\Commands\ListCommand;
use Symfony\Component\Console\Application;

$application = new Application('Composer Git Hooks', '0.3.0');

$application->add(new AddCommand(Hook::getValidHooks()));
$application->add(new RemoveCommand(Hook::getValidHooks()));
$application->add(new ListCommand(Hook::getValidHooks()));

$application->run();
